version : "3.9"
services:
  rtmp:
    image: wws-rtmp-server
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: wws-rtmp-server
    volumes:
      - ./records:/records
